'use client'

import { useState } from 'react'

type Execution = { id: string; state: string; provider?: string; amountUsd: number }
type Result = { plan?: { intent: { type: string; amountUsd: number | null }; policy: { allowed: boolean; needsApproval: boolean; reason: string }; execution: string }; execution?: Execution; quote?: { configured?: boolean; demo?: boolean; message?: string; quoteId?: string }; error?: string }
const states = ['planned', 'awaiting_approval', 'approved', 'quoted', 'signing', 'submitted', 'confirmed']
const stateCopy: Record<string, string> = { planned: 'Intent accepted', awaiting_approval: 'Policy approval gate', approved: 'User approved', quoted: 'Provider quote', signing: 'Wallet signing', submitted: 'Base transaction', confirmed: 'Chain confirmation' }

export default function Home() {
  const [prompt, setPrompt] = useState(''); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [wallet, setWallet] = useState(''); const [walletError, setWalletError] = useState(''); const [approvalLoading, setApprovalLoading] = useState(false)
  async function connectWallet() { setWalletError(''); const ethereum = (window as any).ethereum; if (!ethereum) return setWalletError('Install a browser wallet to connect.'); try { await ethereum.request({ method: 'eth_requestAccounts' }); const chainId = await ethereum.request({ method: 'eth_chainId' }); if (chainId !== '0x2105') await ethereum.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: '0x2105' }] }); const accounts = await ethereum.request({ method: 'eth_accounts' }); setWallet(accounts?.[0]?.toLowerCase() || '') } catch { setWalletError('Wallet connection failed. Please switch to Base Mainnet.') } }
  async function runAgent() { if (!prompt.trim() || loading) return; if (!wallet) { setWalletError('Connect your Base wallet before creating an execution.'); return } setLoading(true); setResult(null); try { const response = await fetch('/api/plan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt }) }); const data = await response.json(); const executionResponse = await fetch('/api/execution', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt, walletAddress: wallet }) }); const executionData = await executionResponse.json(); setResult({ ...data, execution: executionData.execution, error: executionData.error && !data.plan ? executionData.error : data.error }) } catch { setResult({ error: 'Could not reach the Flitzr planner.' }) } finally { setLoading(false) } }
  async function approve() { if (!result?.execution?.id || !wallet || approvalLoading) return; setApprovalLoading(true); try { const response = await fetch('/api/execution/approve', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ executionId: result.execution.id, approval: true, walletAddress: wallet }) }); const data = await response.json(); if (!response.ok) return setResult(prev => ({ ...prev, error: data.error || 'Approval failed' })); setResult(prev => ({ ...prev, execution: data.execution, error: undefined })) } finally { setApprovalLoading(false) } }
  const shortWallet = wallet ? `${wallet.slice(0, 6)}...${wallet.slice(-4)}` : 'Connect Wallet'; const currentState = result?.execution?.state; const stateIndex = currentState ? states.indexOf(currentState) : -1
  return <main className="shell">
    <nav className="nav"><div className="brandWrap"><div className="brandMark">F</div><div><div className="brand">FLITZR</div><div className="brandSub">AUTONOMOUS FINANCE</div></div></div><div className="navRight"><div className="live"><span /> BASE MAINNET · LIVE</div><button className="walletButton" onClick={connectWallet}>{shortWallet}</button></div></nav>
    <section className="hero"><div><div className="eyebrow">Policy-first onchain agent</div><h1>Your money.<br /><span>Your policies.</span><br />Your agent.</h1><p>Turn a financial goal into a controlled execution plan. Flitzr separates intent, policy, approval, routing, and settlement so autonomous actions stay inside the rules you define.</p></div><div className="heroPanel"><div className="panelLabel">SYSTEM STATUS</div><div className="systemRow"><span className="pulse" /> <strong>Agent operational</strong></div><div className="systemMeta">Preview-first execution · Base</div></div></section>
    <section className="metrics"><div className="metric"><span>AGENT</span><strong>READY</strong><small>Policy engine online</small></div><div className="metric"><span>NETWORK</span><strong>BASE</strong><small>Chain ID 8453</small></div><div className="metric"><span>SINGLE LIMIT</span><strong>$25</strong><small>Approval above limit</small></div><div className="metric"><span>DAILY BUDGET</span><strong>$100</strong><small>Policy-controlled</small></div></section>
    <section className="dashboardGrid"><div className="card askCard"><div className="sectionHead"><div><div className="sectionKicker">01 · COMMAND</div><h2>Ask Flitzr</h2></div><span className="modeTag">PREVIEW MODE</span></div><p className="muted">Describe what you want your agent to do. The policy engine checks the request before an execution path is prepared.</p><div className="agent"><input value={prompt} onChange={e => { setPrompt(e.target.value); setResult(null) }} onKeyDown={e => e.key === 'Enter' && runAgent()} placeholder="DCA $20 of ETH every week" /><button onClick={runAgent} disabled={loading}>{loading ? 'Planning…' : 'Plan execution →'}</button></div><div className="examples"><button onClick={() => setPrompt('DCA $20 of ETH every week')}>DCA $20 ETH weekly</button><button onClick={() => setPrompt('Limit buy $20 of ETH')}>Limit buy $20 ETH</button><button onClick={() => setPrompt('Swap $10 to ETH')}>Swap $10 to ETH</button></div>{walletError && <p className="error">{walletError}</p>}{result?.error && <p className="error">{result.error}</p>}{result?.plan && <div className="result"><div className="resultTop"><div><span className="resultLabel">PROPOSED ACTION</span><strong>{result.plan.intent.type.toUpperCase()}</strong></div><span className={result.plan.policy.allowed ? 'okBadge' : 'blockedBadge'}>{result.plan.policy.needsApproval ? 'APPROVAL REQUIRED' : result.plan.policy.allowed ? 'POLICY OK' : 'BLOCKED'}</span></div><p>{result.plan.policy.reason}</p><div className="chips"><span>Base</span><span>{result.plan.intent.amountUsd === null ? 'Amount needed' : `$${result.plan.intent.amountUsd}`}</span><span>{result.plan.policy.allowed ? 'Within policy' : 'Policy blocked'}</span><span>Preview only</span></div>{result.quote?.message && <small>{result.quote.message}</small>}{result.quote?.quoteId && <small>Quote ready: {result.quote.quoteId}</small>}{result.execution?.state === 'awaiting_approval' && <button className="approveButton" onClick={approve} disabled={approvalLoading}>{approvalLoading ? 'Approving…' : 'Approve execution'}</button>}</div>}</div>
    <aside className="card policyCard"><div className="sectionHead"><div><div className="sectionKicker">02 · GUARDRAILS</div><h2>Agent policy</h2></div><span className="shield">✓</span></div><div className="policy"><div><span>Network</span><strong>Base Mainnet</strong></div><div><span>Single trade</span><strong>$25 max</strong></div><div><span>Daily budget</span><strong>$100 max</strong></div><div><span>Approval gate</span><strong>&gt; $25</strong></div></div><div className="policyNote"><span className="dotGreen" /> Deterministic policy · independent of AI</div></aside></section>
    <section className="card providersCard"><div className="sectionHead"><div><div className="sectionKicker">03 · EXECUTION STACK</div><h2>Agents & providers</h2></div><span className="liveSmall">3 CONNECTED</span></div><div className="providers"><div className="provider"><div className="providerIcon bankr">B</div><div><strong>Bankr</strong><span>Agent & wallet operations</span></div><i>READY</i></div><div className="provider"><div className="providerIcon def">D</div><div><strong>Definitive Flash</strong><span>DCA & advanced order planning</span></div><i>ADAPTER</i></div><div className="provider"><div className="providerIcon uni">U</div><div><strong>Uniswap</strong><span>Spot routing on Base</span></div><i>ROUTER</i></div></div></section>
    {result?.execution && <section className="card timelineCard"><div className="sectionHead"><div><div className="sectionKicker">04 · OPERATIONS</div><h2>Execution timeline</h2></div><span className="stateBadge">{result.execution.state.replace('_', ' ')}</span></div><div className="timeline">{states.map((state, index) => <div className={`step ${index <= stateIndex ? 'active' : ''}`} key={state}><span className="dot" /><div><strong>{state.replace('_', ' ')}</strong><small>{stateCopy[state]}</small></div></div>)}</div><p className="previewNote">Preview mode is active. Approval changes state only; no transaction is broadcast.</p></section>}
    <section className="lowerGrid"><div className="card activityCard"><div className="sectionHead"><div><div className="sectionKicker">05 · AUDIT</div><h2>Activity</h2></div><span className="liveSmall">LOCAL SESSION</span></div><div className="activity"><div><span className="activityDot green" /><div><strong>Policy engine</strong><span>{result ? 'Request evaluated against Base guardrails' : 'Waiting for a command'}</span></div><time>NOW</time></div><div><span className="activityDot" /><div><strong>Execution layer</strong><span>{result?.execution ? `${result.execution.provider || 'provider'} · ${result.execution.state}` : 'No execution created'}</span></div><time>—</time></div><div><span className="activityDot" /><div><strong>Settlement</strong><span>Broadcast disabled in preview mode</span></div><time>SAFE</time></div></div></div><div className="card treasuryCard"><div className="sectionHead"><div><div className="sectionKicker">06 · TREASURY</div><h2>Wallet session</h2></div><span className="shield">✓</span></div><div className="treasuryValue">{wallet ? `${wallet.slice(0, 6)}…${wallet.slice(-4)}` : 'Not connected'}</div><p className="muted">The browser wallet is used for user identity and future signing. Server-side sponsor keys never enter the client.</p><button className="secondaryButton" onClick={connectWallet}>{wallet ? 'Reconnect wallet' : 'Connect Base wallet'}</button></div></section>
    <footer><div>FLITZR <span>·</span> RUNTIME AGENT WEEK BUILD</div><div>POLICY-FIRST · PREVIEW-FIRST · BASE</div></footer>
  </main>
}
