'use client'

import { useMemo, useState } from 'react'
import { usePrivy, useWallets } from '@privy-io/react-auth'

type Agent={name:string;category:string;rarity:string;trend:string;tvl:string;days:number;success:string;metric:string;metricLabel:string;restraint:number;thesis:string}
const AGENTS:Agent[]=[
{name:'CompoundKeeper',category:'Yield Optimisation',rarity:'LEGENDARY',trend:'Rising',tvl:'$3.40M',days:610,success:'98%',metric:'22.7%',metricLabel:'NET APY',restraint:87,thesis:'Long-running yield allocation strategy focused on stable, risk-bounded compounding.'},
{name:'LatticeBot',category:'Rebalancing',rarity:'EPIC',trend:'Rising',tvl:'$2.10M',days:520,success:'97%',metric:'-2.8%',metricLabel:'MAX DRAWDOWN',restraint:82,thesis:'Rebalances a diversified Base portfolio when configured allocation bands are crossed.'},
{name:'MarginMinder',category:'Health Factor Monitoring',rarity:'EPIC',trend:'Rising',tvl:'$1.90M',days:480,success:'97%',metric:'1.78',metricLabel:'MIN HEALTH FACTOR',restraint:84,thesis:'Monitors lending positions and proposes defensive actions before health factors deteriorate.'},
{name:'DriftGuard',category:'Rebalancing',rarity:'RARE',trend:'Rising',tvl:'$1.24M',days:410,success:'96%',metric:'12%',metricLabel:'REBALANCES / YR',restraint:75,thesis:'Low-frequency portfolio rebalancer designed to limit unnecessary turnover.'},
{name:'YieldCartographer',category:'Yield Optimisation',rarity:'RARE',trend:'Hot',tvl:'$1.45M',days:300,success:'92%',metric:'18.4%',metricLabel:'NET APY',restraint:78,thesis:'Maps available yield venues and keeps allocations inside a configurable risk envelope.'},
{name:'GridForge',category:'Grid Trading',rarity:'RARE',trend:'Rising',tvl:'$980K',days:380,success:'94%',metric:'4.2%',metricLabel:'MAX DRAWDOWN',restraint:63,thesis:'Range-based grid strategy with explicit order and spend boundaries.'},
{name:'AllocaFlow',category:'Rebalancing',rarity:'UNCOMMON',trend:'Hot',tvl:'$640K',days:260,success:'91%',metric:'8%',metricLabel:'REBALANCES / YR',restraint:76,thesis:'Rules-based allocation agent for maintaining target portfolio weights.'},
{name:'HealthSentinel',category:'Health Factor Monitoring',rarity:'RARE',trend:'Rising',tvl:'$760K',days:340,success:'95%',metric:'1.62',metricLabel:'MIN HEALTH FACTOR',restraint:84,thesis:'Watches lending health factors and surfaces liquidation-risk conditions.'},
{name:'CushionBot',category:'Health Factor Monitoring',rarity:'COMMON',trend:'Cooling',tvl:'$410K',days:210,success:'90%',metric:'1.45',metricLabel:'MIN HEALTH FACTOR',restraint:72,thesis:'Conservative monitoring with a wider safety cushion and slower intervention cadence.'},
{name:'HarvestHand',category:'Yield Optimisation',rarity:'UNCOMMON',trend:'Cooling',tvl:'$210K',days:150,success:'85%',metric:'14.1%',metricLabel:'NET APY',restraint:57,thesis:'Yield rotation assistant that prefers fewer, larger allocation changes.'},
{name:'PoolPathfinder',category:'Yield Optimisation',rarity:'COMMON',trend:'Hot',tvl:'$15K',days:28,success:'77%',metric:'9.8%',metricLabel:'NET APY',restraint:57,thesis:'Early-stage route discovery agent for comparing pools and estimated yield.'},
{name:'WeightWatch',category:'Rebalancing',rarity:'COMMON',trend:'Hot',tvl:'$22K',days:35,success:'79%',metric:'15%',metricLabel:'REBALANCES / YR',restraint:57,thesis:'Lightweight portfolio drift monitor for small allocations.'},
{name:'LiquidationLookout',category:'Health Factor Monitoring',rarity:'UNCOMMON',trend:'Rising',tvl:'$330K',days:200,success:'90%',metric:'1.35',metricLabel:'MIN HEALTH FACTOR',restraint:69,thesis:'Risk monitor focused on detecting rapidly falling lending health factors.'},
{name:'BoxRunner',category:'Grid Trading',rarity:'UNCOMMON',trend:'Cooling',tvl:'$95K',days:90,success:'83%',metric:'-9.1%',metricLabel:'MAX DRAWDOWN',restraint:61,thesis:'Compact grid strategy for bounded markets with strict order sizing.'},
{name:'StepTrader',category:'Grid Trading',rarity:'COMMON',trend:'Rising',tvl:'$70K',days:70,success:'86%',metric:'6.4%',metricLabel:'MAX DRAWDOWN',restraint:64,thesis:'Step-based trading strategy with a narrow execution range.'},
{name:'BalancerBee',category:'Rebalancing',rarity:'UNCOMMON',trend:'Cooling',tvl:'$180K',days:120,success:'88%',metric:'5%',metricLabel:'REBALANCES / YR',restraint:70,thesis:'Simple target-weight rebalancer with a low activity preference.'}
]
const categories=['All 16','Rebalancing','Grid Trading','Yield Optimisation','Health Factor Monitoring']

export default function AgentMarketplace(){
 const{ready,authenticated,login}=usePrivy();const{wallets}=useWallets()
 const[category,setCategory]=useState('All 16');const[rarity,setRarity]=useState('All');const[trend,setTrend]=useState('All');const[selected,setSelected]=useState<Agent|null>(null);const[cap,setCap]=useState('500');const[shadow,setShadow]=useState(true);const[days,setDays]=useState('30');const[actions,setActions]=useState<string[]>(['deposit','withdraw','claim']);const[notice,setNotice]=useState('')
 const wallet=wallets[0]?.address
 const filtered=useMemo(()=>AGENTS.filter(a=>(category==='All 16'||a.category===category)&&(rarity==='All'||a.rarity===rarity)&&(trend==='All'||a.trend===trend)),[category,rarity,trend])
 const toggleAction=(a:string)=>setActions(v=>v.includes(a)?v.filter(x=>x!==a):[...v,a])
 async function activate(){if(!selected)return;if(!authenticated){await login();return}const amount=Number(cap);if(!Number.isFinite(amount)||amount<0){setNotice('Enter a valid spend cap.');return}setNotice('Agent activated in '+(shadow?'SHADOW':'LIVE-READY')+' mode · cap $'+amount.toLocaleString()+' · '+days+' days · '+actions.length+' scoped actions. No transaction was broadcast by this activation screen.');setSelected(null)}
 return <section className="mp-shell">
  <header className="mp-nav"><div className="mp-brand"><div className="mp-logo">F</div><div><strong>FLITZR</strong><small>AGENT MARKETPLACE</small></div></div><div className="mp-navlinks"><span>Discover</span><span>Compare</span><span>Activate</span><span className="mp-network">BASE · 8453 · {authenticated?'CONNECTED':'READY'}</span><button onClick={()=>authenticated?setNotice('Wallet is connected.'):login()} disabled={!ready}>{authenticated&&wallet?wallet.slice(0,6)+'…'+wallet.slice(-4):'Connect Wallet'}</button></div></header>
  <div className="mp-intro"><div><div className="mp-eyebrow">AGENT MARKETPLACE · SEEDED DATASET</div><h1>Find the right agent.<br/><span>Understand the risk.</span><br/>Activate with limits.</h1><p>Browse agent strategies by category, rarity, and track record. Open a thesis, inspect risk signals, then configure scoped permissions before any execution.</p></div><div className="mp-statbox"><strong>16</strong><span>AGENTS AVAILABLE</span><small>Seeded · reviewable · no blank checks</small></div></div>
  <div className="mp-metrics"><div><span>REBALANCING</span><b>4 agents</b><small>88% avg success</small></div><div><span>GRID TRADING</span><b>4 agents</b><small>86% avg success</small></div><div><span>YIELD OPTIMISATION</span><b>4 agents</b><small>89% avg success</small></div><div><span>HEALTH FACTOR</span><b>4 agents</b><small>89% avg success</small></div></div>
  <div className="mp-work"><aside className="mp-filters"><label>AGENT CATEGORY</label>{categories.map(c=><button className={category===c?'on':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}<label>RARITY</label><select value={rarity} onChange={e=>setRarity(e.target.value)}><option>All</option><option>LEGENDARY</option><option>EPIC</option><option>RARE</option><option>UNCOMMON</option><option>COMMON</option></select><label>TRENDING</label><select value={trend} onChange={e=>setTrend(e.target.value)}><option>All</option><option>Hot</option><option>Rising</option><option>Cooling</option></select><div className="mp-help"><b>WHAT DO THESE TERMS MEAN?</b><p>TVL, success rate, drawdown/health factor, restraint and trend are shown together so the operating envelope is visible before activation.</p></div></aside>
   <main><div className="mp-toolbar"><div><b>Compare strategy, track record, and risk.</b><span>TVL managed, success rate, key risk metric, and restraint — on one card.</span></div><span>{filtered.length} agents</span></div><div className="mp-grid">{filtered.map(a=><article className="mp-card" key={a.name} onClick={()=>{setSelected(a);setNotice('')}}><div className="mp-cardtop"><span className="mp-pill">{a.rarity}</span><span className="mp-trend">{a.trend==='Hot'?'🔥':a.trend==='Rising'?'↗':'→'} {a.trend}</span></div><h3>{a.name}</h3><small>{a.category}</small><div className="mp-values"><div><b>{a.tvl}</b><span>TVL MANAGED</span></div><div><b>{a.days}d</b><span>TRACK RECORD</span></div><div><b>{a.success}</b><span>SUCCESS RATE</span></div><div><b>{a.metric}</b><span>{a.metricLabel}</span></div></div><div className="mp-restraint"><span>Restraint</span><b>{a.restraint}%</b><i><em style={{width:a.restraint+'%'}}/></i></div><button>Open agent →</button></article>)}</div></main></div>
  <div className="mp-swapnote"><div><b>Swap · Crypto & Tokenized Assets</b><span>Live swap execution remains wallet-signed. The marketplace itself does not broadcast a transaction.</span></div><span className="mp-mock">LIVE-READY · EXPLICIT SIGNING</span></div>{notice&&<div className="mp-notice">{notice}</div>}
  {selected&&<div className="mp-overlay" onClick={()=>setSelected(null)}><div className="mp-modal" onClick={e=>e.stopPropagation()}><button className="mp-close" onClick={()=>setSelected(null)}>×</button><div className="mp-eyebrow">AGENT DETAIL</div><h2>{selected.name}</h2><p>{selected.thesis}</p><div className="mp-detailgrid"><div><b>{selected.tvl}</b><span>TVL MANAGED</span></div><div><b>{selected.days}d</b><span>TRACK RECORD</span></div><div><b>{selected.success}</b><span>SUCCESS RATE</span></div><div><b>{selected.metric}</b><span>{selected.metricLabel}</span></div></div><div className="mp-boundary"><h4>Set the boundaries before this agent can act</h4><label>SHADOW WINDOW<select value={days} onChange={e=>setDays(e.target.value)}><option>3</option><option>7</option><option>30</option></select> days observe</label><label>SPEND CAP (USD) — MAX CAPITAL AT RISK<input value={cap} onChange={e=>setCap(e.target.value)} inputMode="decimal"/></label><div className="mp-blast">Blast radius: <b>{'$'+Number(cap||0).toLocaleString()}</b> · restraint {selected.restraint}%</div><label className="mp-toggle"><input type="checkbox" checked={shadow} onChange={e=>setShadow(e.target.checked)}/> Shadow mode — execution delayed</label><div className="mp-actions"><span>ALLOWED ACTIONS</span>{['deposit','withdraw','claim','swap'].map(a=><button key={a} className={actions.includes(a)?'sel':''} onClick={()=>toggleAction(a)}>{actions.includes(a)?'✓ ':''}{a}</button>)}</div><div className="mp-expiry">EXPIRY · {days} DAYS · REVOKE ANYTIME</div><button className="mp-activate" onClick={activate}>{authenticated?'Confirm activation':'Connect wallet to activate'}</button><small>Activation configures the boundary. Live fund movement still requires the wallet/provider transaction flow and explicit signature.</small></div></div></div>}
 </section>
}